# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: assignment4
    - run: npm run build --if-present
      working-directory: assignment4
    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
      working-directory: assignment4
    - run: bash <(curl -s https://codecov.io/bash)
    
   # - name: Upload coverage to Codecov
   #   uses: codecov/codecov-action@v1
   #   with:
   #    token: ${{ secrets.CODECOV_TOKEN }}
   
      
  
